### ISSUE TITLE
KeyError: 'test_lossESR_final' running the trainer in google colab

### ISSUE THREAD

**Issue by pilali** [AidaDSP/Automated-GuitarAmpModelling#8]
I recently discoverd this promising tool. I've been trying to run the trainer in google colab using different input/target files. It's constently failing right after I launch the trainig. Any help/idea ? Thanks.

/content/Automated-GuitarAmpModelling/CoreAudioML/networks.py:28: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  def forward(ctx, input, min, max):
/content/Automated-GuitarAmpModelling/CoreAudioML/networks.py:33: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  def backward(ctx, grad_output):

args.model = SimpleRNN
args.device = MOD-DWARF
args.file_name = mudhoney2high
args.input_size = 1
args.hidden_size = 16
args.unit_type = LSTM
args.loss_fcns = {'ESR': 0.75, 'DC': 0.25}
args.skip_con = 1
args.pre_filt = A-Weighting
existing model file found, loading network.. continuing training..
/usr/local/lib/python3.10/dist-packages/torch/__init__.py:955: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:432.)
  _C._set_default_tensor_type(t)
/usr/local/lib/python3.10/dist-packages/torch/optim/lr_scheduler.py:60: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(
  0% 1/200 [00:01<03:21,  1.01s/it]
Traceback (most recent call last):
  File "/content/Automated-GuitarAmpModelling/dist_model_recnet.py", line 238, in <module>
    val_output, val_loss = network.process_data(dataset.subsets['val'].data['input'][0],
  File "/content/Automated-GuitarAmpModelling/CoreAudioML/networks.py", line 777, in process_data
    output[l * chunk:(l + 1) * chunk] = self(input_data[l * chunk:(l + 1) * chunk])
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/Automated-GuitarAmpModelling/CoreAudioML/networks.py", line 691, in forward
    x, self.hidden = self.rec(x, self.hidden)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/rnn.py", line 917, in forward
    result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-15-c34516351da8>](https://localhost:8080/#) in <cell line: 46>()
     44 model_dir = f"/content/Automated-GuitarAmpModelling/Results/{file_name}_{config_file}-{skip_con}"
     45 step = max(step, 2)
---> 46 print("Training done!\nESR after training: ", extract_best_esr_model(model_dir)[1])

[/content/Automated-GuitarAmpModelling/colab_functions.py](https://localhost:8080/#) in extract_best_esr_model(dirpath)
    161   with open(stats_file) as json_file:
    162     stats_data = json.load(json_file)
--> 163     test_lossESR_final = stats_data['test_lossESR_final']
    164     test_lossESR_best = stats_data['test_lossESR_best']
    165     esr = min(test_lossESR_final, test_lossESR_best)

KeyError: 'test_lossESR_final'

**Comment by LievenDeeVee** [comment]
I encounter the same issue.

Oct 4th 2024

```
/content/Automated-GuitarAmpModelling/CoreAudioML/networks.py:28: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  def forward(ctx, input, min, max):
/content/Automated-GuitarAmpModelling/CoreAudioML/networks.py:33: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  def backward(ctx, grad_output):

args.model = SimpleRNN
args.device = MOD-DWARF
args.file_name = PF-SpacePirate
args.input_size = 1
args.hidden_size = 16
args.unit_type = LSTM
args.loss_fcns = {'ESR': 0.75, 'DC': 0.25}
args.skip_con = 0
args.pre_filt = A-Weighting
existing model file found, loading network.. continuing training..
/usr/local/lib/python3.10/dist-packages/torch/__init__.py:955: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:432.)
  _C._set_default_tensor_type(t)
/usr/local/lib/python3.10/dist-packages/torch/optim/lr_scheduler.py:60: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(
  0% 1/540 [00:03<34:53,  3.88s/it]
Traceback (most recent call last):
  File "/content/Automated-GuitarAmpModelling/dist_model_recnet.py", line 238, in <module>
    val_output, val_loss = network.process_data(dataset.subsets['val'].data['input'][0],
  File "/content/Automated-GuitarAmpModelling/CoreAudioML/networks.py", line 777, in process_data
    output[l * chunk:(l + 1) * chunk] = self(input_data[l * chunk:(l + 1) * chunk])
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/Automated-GuitarAmpModelling/CoreAudioML/networks.py", line 698, in forward
    x, self.hidden = self.rec(x, self.hidden)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/rnn.py", line 917, in forward
    result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-6-6e2df7b97e5b> in <cell line: 46>()
     44 model_dir = f"/content/Automated-GuitarAmpModelling/Results/{file_name}_{config_file}-{skip_con}"
     45 step = max(step, 2)
---> 46 print("Training done!\nESR after training: ", extract_best_esr_model(model_dir)[1])

/content/Automated-GuitarAmpModelling/colab_functions.py in extract_best_esr_model(dirpath)
    161   with open(stats_file) as json_file:
    162     stats_data = json.load(json_file)
--> 163     test_lossESR_final = stats_data['test_lossESR_final']
    164     test_lossESR_best = stats_data['test_lossESR_best']
    165     esr = min(test_lossESR_final, test_lossESR_best)

KeyError: 'test_lossESR_final'
```

**Comment by falkTX** [comment]
are you sure this is a new error?
the line that says:

> RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

is very suspicious.

can you try with wav files you know have worked before?

**Comment by falkTX** [comment]
Looking more about this online the error seems to be a generic one that is triggered for a variety of reasons.
I suspect Google updated some collab internals that broke the trainer code. :(

**Comment by pilali** [comment]
It’s seems related to the use of GPU. Both files are 27 360 042 octets. It still fails without GPU for other reasons:
"Generating model file: mud_LSTM-8-0.json
/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/input_layer.py:26: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(
Traceback (most recent call last):
  File "/content/Automated-GuitarAmpModelling/modelToKeras.py", line 85, in <module>
    lstm_layer = keras.layers.LSTM(hidden_size, activation=None, weights=lstm_weights, return_sequences=True, recurrent_activation=None, use_bias=bias_fl, unit_forget_bias=False)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/lstm.py", line 486, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py", line 204, in __init__
    super().__init__(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/layers/layer.py", line 266, in __init__
    raise ValueError(
ValueError: Unrecognized keyword arguments passed to LSTM: {'weights': [array([[ 9.93221812e-03, -1.71120882e-01,  4.29465055e-01,
         7.36645341e-01,  1.82832748e-01, -8.08661506e-02,
        -5.43025911e-01,  9.28551912e-01, -2.64538452e-03,
        -8.04659054e-02, -1.56875998e-01, -2.08989829e-01,
         1.75829045e-02 [...]"

**Comment by MaxPayne86** [comment]
Ok I think the first warning provide some context:

```
UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives
```
Colab recently switched to torch 2.1, in which several changes were made: notably the way we move data on gpu, if available.

We need to assume that those trainings were putting data on the cpu: and this lead to the final error

```
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
```

I am almost sure it's happening because data was on cpu, however I've added a check in CoreAudioML/dataset.py to ensure data added in the DataSet class is indeed contiguous

I've placed all the fixes into feature/support-torch21, need test!

**Comment by pilali** [comment]
I just tested the notebook from the support-torch21 branch, with T4 GPU. Step 1.3 result is:
"Input file name: /content/drive/MyDrive/pédales/mudhoney2high/input.wav
Target file name: /content/drive/MyDrive/pédales/mudhoney2high/target.wav
Input rate: 48000 length: 9119999 [samples]
Target rate: 48000 length: 9119999 [samples]
Preprocessing the training data...

Data prepared! you can now move to step 2: TRAINING"
Step 2: "RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input."

I assume any GPU in colab is ok, right?

**Comment by MaxPayne86** [comment]
Yes every GPU (cuda backend) is fine, do I need to assume you started from a clean Colab and so can you check the sha in git submodule CoreAudioML to be 1c35b7d? If so, then do you have a more verbose log output plz? Thx a lot for the testing!

**Comment by pilali** [comment]
Yes I started from a fresh colab. Unfortunately I lost the connection to the environnement, so I can't check that CoreAudio sha. But I kept the complete output in a file:

/content/Automated-GuitarAmpModelling/CoreAudioML/networks.py:28: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  def forward(ctx, input, min, max):
/content/Automated-GuitarAmpModelling/CoreAudioML/networks.py:33: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  def backward(ctx, grad_output):

args.model = SimpleRNN
args.device = MOD-DWARF
args.file_name = mudhoney2high
args.input_size = 1
args.hidden_size = 16
args.unit_type = LSTM
args.loss_fcns = {'ESR': 0.75, 'DC': 0.25}
args.skip_con = 0
args.pre_filt = A-Weighting
no saved model found, creating new network
/usr/local/lib/python3.10/dist-packages/torch/__init__.py:955: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:432.)
  _C._set_default_tensor_type(t)
/usr/local/lib/python3.10/dist-packages/torch/optim/lr_scheduler.py:60: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(
  0% 1/200 [00:02<09:14,  2.79s/it]
Traceback (most recent call last):
  File "/content/Automated-GuitarAmpModelling/dist_model_recnet.py", line 238, in <module>
    val_output, val_loss = network.process_data(dataset.subsets['val'].data['input'][0],
  File "/content/Automated-GuitarAmpModelling/CoreAudioML/networks.py", line 777, in process_data
    output[l * chunk:(l + 1) * chunk] = self(input_data[l * chunk:(l + 1) * chunk])
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/Automated-GuitarAmpModelling/CoreAudioML/networks.py", line 698, in forward
    x, self.hidden = self.rec(x, self.hidden)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/rnn.py", line 917, in forward
    result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-156e4608184f> in <cell line: 46>()
     44 model_dir = f"/content/Automated-GuitarAmpModelling/Results/{file_name}_{config_file}-{skip_con}"
     45 step = max(step, 2)
---> 46 print("Training done!\nESR after training: ", extract_best_esr_model(model_dir)[1])

/content/Automated-GuitarAmpModelling/colab_functions.py in extract_best_esr_model(dirpath)
    161   with open(stats_file) as json_file:
    162     stats_data = json.load(json_file)
--> 163     test_lossESR_final = stats_data['test_lossESR_final']
    164     test_lossESR_best = stats_data['test_lossESR_best']
    165     esr = min(test_lossESR_final, test_lossESR_best)

KeyError: 'test_lossESR_final'


``

**Comment by pilali** [comment]
So I ran it again in a clean environnement. URL is https://colab.research.google.com/github/AidaDSP/Automated-GuitarAmpModelling/blob/feature/support-torch21/AIDA_X_Model_Trainer.ipynb so I assure I am running the right notebook.

Same error. Code in the CoreAudioML/dataset.py is 

113                    self.subsets[set_names[n]].add_data(np_data[0], raw_audio[n], ext, cond_val)
115                self.subsets[set_names[0]].add_data(np_data[0], raw_audio, ext, cond_val)

Shouldn't be
113                  self.subsets[set_names[n]].add_data(np_data[0], np.ascontiguousarray(raw_audio[n]), ext, cond_val)
115                self.subsets[set_names[0]].add_data(np_data[0], np.ascontiguousarray(raw_audio), ext, cond_val)

?

**Comment by MaxPayne86** [comment]
ah I see it now, thanks. I've updated AIDA_X_Model_Trainer.ipynb to fetch test branch feature/support-torch21, otherwise we are looping with old version.

In addition to that, I've pushed a new branch bug-fix/force-required-deps in which I've added a step to prune default Colab torch and cuDNN versions and install known versions that have been tested!

Let me know, once correct dependencies are installed a restart of the runtime is prompted in Colab, it should work fine then. Regarding eature/support-torch21, we can still test it but with a more relaxed mindset.

**Comment by pilali** [comment]
I tried the new notebook and had this error:  "NameError: name ‘torch’ is not defined."

At this point I think it’s very important for me to confess that I have absolutely ZERO skills at coding. But I’m trying really hard to understand :D
So I took the liberty to add these two lines at the beginning of cell O: 

#Check PyTorch and CUDA versions
import torch
import re

Which gave me this : 


WARNING: Your environment has PyTorch 2.0.1+cu117 and CUDA 11.7. This environment is not supported.
Proceeding to install required dependencies...
Found existing installation: torch 2.0.1+cu117
Uninstalling torch-2.0.1+cu117:
  Successfully uninstalled torch-2.0.1+cu117
Found existing installation: torchvision 0.15.2+cu117
Uninstalling torchvision-0.15.2+cu117:
  Successfully uninstalled torchvision-0.15.2+cu117
Found existing installation: torchaudio 2.0.2+cu117
Uninstalling torchaudio-2.0.2+cu117:
  Successfully uninstalled torchaudio-2.0.2+cu117
Found existing installation: tensorflow 2.11.0
Uninstalling tensorflow-2.11.0:
  Successfully uninstalled tensorflow-2.11.0
Found existing installation: tensorboard 2.11.0
Uninstalling tensorboard-2.11.0:
  Successfully uninstalled tensorboard-2.11.0
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting torch==2.0.1+cu117
  Downloading https://download.pytorch.org/whl/cu117/torch-2.0.1%2Bcu117-cp310-cp310-linux_x86_64.whl (1843.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 GB 210.7 MB/s eta 0:00:00
Collecting torchvision==0.15.2+cu117
  Downloading https://download.pytorch.org/whl/cu117/torchvision-0.15.2%2Bcu117-cp310-cp310-linux_x86_64.whl (6.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.1/6.1 MB 285.2 MB/s eta 0:00:00
Collecting torchaudio==2.0.2+cu117
  Downloading https://download.pytorch.org/whl/cu117/torchaudio-2.0.2%2Bcu117-cp310-cp310-linux_x86_64.whl (4.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 207.8 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch==2.0.1+cu117) (3.16.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch==2.0.1+cu117) (4.12.2)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch==2.0.1+cu117) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch==2.0.1+cu117) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch==2.0.1+cu117) (3.1.4)
Requirement already satisfied: triton==2.0.0 in /usr/local/lib/python3.10/dist-packages (from torch==2.0.1+cu117) (2.0.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from torchvision==0.15.2+cu117) (1.26.4)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from torchvision==0.15.2+cu117) (2.32.3)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.10/dist-packages (from torchvision==0.15.2+cu117) (10.4.0)
Requirement already satisfied: cmake in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch==2.0.1+cu117) (3.30.4)
Requirement already satisfied: lit in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch==2.0.1+cu117) (18.1.8)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch==2.0.1+cu117) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->torchvision==0.15.2+cu117) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->torchvision==0.15.2+cu117) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->torchvision==0.15.2+cu117) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->torchvision==0.15.2+cu117) (2024.8.30)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->torch==2.0.1+cu117) (1.3.0)
Installing collected packages: torch, torchvision, torchaudio
Successfully installed torch-2.0.1+cu117 torchaudio-2.0.2+cu117 torchvision-0.15.2+cu117
WARNING: The following packages were previously imported in this runtime:
  [nvfuser,torch]
You must restart the runtime in order to use newly installed versions.

Collecting tensorflow==2.11.0
  Downloading tensorflow-2.11.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.1 kB)
Collecting tensorboard==2.11.0
  Downloading tensorboard-2.11.0-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.11.0) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.11.0) (1.6.3)
Requirement already satisfied: flatbuffers>=2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.11.0) (24.3.25)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.11.0) (0.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.11.0) (0.2.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.11.0) (1.64.1)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.11.0) (3.11.0)
Requirement already satisfied: keras<2.12,>=2.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.11.0) (2.11.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.11.0) (18.1.1)
Requirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.11.0) (1.26.4)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.11.0) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.11.0) (24.1)
Requirement already satisfied: protobuf<3.20,>=3.9.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.11.0) (3.19.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.11.0) (71.0.4)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.11.0) (1.16.0)
Requirement already satisfied: tensorflow-estimator<2.12,>=2.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.11.0) (2.11.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.11.0) (2.4.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.11.0) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.11.0) (1.16.0)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.11.0) (0.37.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard==2.11.0) (2.27.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard==2.11.0) (0.4.6)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard==2.11.0) (3.7)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard==2.11.0) (2.32.3)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard==2.11.0) (0.6.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard==2.11.0) (1.8.1)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard==2.11.0) (3.0.4)
Requirement already satisfied: wheel>=0.26 in /usr/local/lib/python3.10/dist-packages (from tensorboard==2.11.0) (0.44.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard==2.11.0) (5.5.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard==2.11.0) (0.4.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard==2.11.0) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard==2.11.0) (1.3.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard==2.11.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard==2.11.0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard==2.11.0) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard==2.11.0) (2024.8.30)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard==2.11.0) (2.1.5)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard==2.11.0) (0.6.1)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard==2.11.0) (3.2.2)
Downloading tensorflow-2.11.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (588.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 588.3/588.3 MB 228.3 MB/s eta 0:00:00
Downloading tensorboard-2.11.0-py3-none-any.whl (6.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 280.6 MB/s eta 0:00:00
Installing collected packages: tensorboard, tensorflow
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tf-keras 2.17.0 requires tensorflow<2.18,>=2.17, but you have tensorflow 2.11.0 which is incompatible.
Successfully installed tensorboard-2.11.0 tensorflow-2.11.0

I refused to restart the environment and move on through the next steps and IT WORKED!!!

That’s pretty messy for sure but… I hope it might help you finding a cleaner fix.
Thanks you for your time!

**Comment by MaxPayne86** [comment]
I have pushed a small fix, adding

```
import torch
import re
```

as suggested by you. It should be ok now, so I will proceed to merge bug-fix/force-required-deps into current default branch aidadsp_devel. Thanks for the testing!

**Comment by MaxPayne86** [comment]
Fixed with 000702af9617d7d72dd697988198e698a42cc9b9

**Comment by pilali** [comment]
By the way that was the first pedal I was able to train for Aida, I must say that the result is far more convincing than other solutions I tried. Great job guys!
